# Generated by Django 4.1.5 on 2023-02-06 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('bio', models.TextField(default='This is my bio')),
                ('theme', models.BooleanField(default=True)),
                ('notifications', models.BooleanField(default=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('gps_coords', models.CharField(blank=True, max_length=2000, null=True)),
                ('likes', models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
